version: '3.8'

services:
  software-and-data-integrity-failures:
    build: ./vuln-lab
    restart: unless-stopped
    ports: 
      - "8008:80"
    volumes:
      - ./vuln-lab/resource:/var/www/html
