version: '3.8'

services:
  ientification-and-authentication-failure:
    build: ./vuln-lab
    restart: unless-stopped
    ports: 
      - "7007:80"
    volumes:
      - ./vuln-lab/resource:/var/www/html
